name: Compile and Test

on:
  push:

env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  compile-and-test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11

      - name: Cache packages
        uses: actions/cache@v2
        with:
          path: ~/.ivy2/cache
          # key include hash of build.sbt so it is invalidated on any change to build.sbt
          key: ${{ runner.os }}-ivy2-${{ hashFiles('**/build.sbt') }}
          restore-keys: ${{ runner.os }}-ivy2-

      - name: Compile
        run: sbt compile

      - name: Test
        run: sbt jacoco

      - name: Upload test report
        uses: actions/upload-artifact@v2
        with:
          name: test-report
          path: target/test-reports/

      - name: Upload coverage report
        uses: actions/upload-artifact@v2
        with:
          name: coverage-report
          path: target/scala-2.12/jacoco/report/
