name: Scala CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build-on-ubuntu:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Run tests
      run: sbt test
    - name: Run compile
      run: sbt compile
    - name: Build package
      run: sbt package
    - name: Build assembly
      run: sbt assembly
  build-on-mac:

    runs-on: macOS-latest

    steps:
    - run: |
        brew install sbt
    - uses: actions/checkout@v2
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Run tests
      run: sbt test
    - name: Run compile
      run: sbt compile
    - name: Build package
      run: sbt package
    - name: Build assembly
      run: sbt assembly
    - name: upload assembly
      uses: actions/upload-artifact@v1
      with:
        name: modelardb-macos
        path: target/scala-2.11/ModelarDB-assembly-1.0.jar
    
